### ISSUE TITLE
Add more option in EnjoyCJZC.ini

### ISSUE THREAD

**Issue by thanhnguyen1121** [Onuq007/PubGFX#1]
how can i add more property in "EnjoyCJZC.ini" like +CVars=r.MobileContentScaleFactor=1.49, etc

**Comment by Onuq007** [comment]
Ok.
Give me examples.
= 2 - 1440p 
= 1 - HD + 
Etc.

**Comment by thanhnguyen1121** [comment]
yup... reallt i can add more property. We need add property below [FansCustom]
